from typing import Any, Protocol

from fastapi import WebSocket
from pydantic import BaseModel


class IWebsocketController(Protocol):
    def register_connect(self, user_id: int, connection: WebSocket) -> None: ...
    def register_disconnect(self, user_id: int) -> None: ...
    def is_connected(self, user_id: int) -> bool: ...
    async def send_payload(self, user_id: int, dto: BaseModel) -> None: ...
    async def broadcast_payload(self, dto: BaseModel) -> None: ...
    async def run_action(
        self, user_id: int, action_name: str, action_data: dict[str, Any]
    ) -> None: ...
