from app.controllers.message.dto import ChatMessageDto
from app.models.chat import ChatMessageModel
from typing import Protocol


class IMessageController(Protocol):
    async def create(
        self, from_user_id: int, to_user_id: int, contents: str
    ) -> ChatMessageDto: ...
    async def delete(self, message_id: int) -> None: ...
    async def get_for_users(
        self, from_user_id: int, to_user_id: int
    ) -> list[ChatMessageDto]: ...
    async def mark_readed(self, message_id: int) -> ChatMessageDto: ...
    async def get_user_chats(self, user_id: int) -> list[int]: ...
    async def get_by_id(self, message_id: int) -> ChatMessageDto: ...
